
## Workspace Linux configuration.
## 
## Note: setup an Ubuntu-based one to align better with CSAA
##
FROM amazonlinux:latest

RUN yum -y update && yum -y install \
  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
  gcc \
  git \
  htop \
  jq \
  libffi-dev \
  libffi-devel \
  libssl-dev \
  libxslt-devel \
  libxml2-devel \
  pyOpenSSL \
  python27 \
  python27-cffi \
  python27-dev \
  python27-devel \
  python2-pip \
  openssl-dev \
  openssl-devel \
  tmux \
  htop \
  tree \
  vim \
  wget \
  zip


RUN pip install \
  ansible \
  aws-adfs \
  awscli \
  boto3

# TODO: Add cf CLI
# Install usage-report plugin
# USAGE: cf usage-report -o <space>
#RUN cf install-plugin 'Usage Report' -r CF-Community


# Set flag to force container updates
ARG FORCE_UPGRADE=no
RUN yum check-update -y && yum update -y

# Run versions check
RUN \
  ansible --version; \
  aws --version; \
  aws-adfs --version; \
  git --version; \
  htop --version; \
  jq --version; \
  tmux -V; \
  tree --version; \
  wget --version
