
## Workspace Linux configuration.
## 
## Note: setup an Ubuntu-based one to align better with CSAA
##
FROM amazonlinux:latest

RUN yum -y update && yum -y install \
  epel-release \
  gcc \
  git \
  htop \
  jq \
  libffi-dev \
  libffi-devel \
  libssl-dev \
  libxslt-devel \
  libxml2-devel \
  pyOpenSSL \
  python27 \
  python27-cffi \
  python27-dev \
  python27-devel \
  python2-pip \
  openssl-dev \
  openssl-devel \
  tmux \
  tree \
  vim \
  wget \
  zip


RUN pip install \
  ansible \
  aws-adfs \
  awscli \
  boto3

RUN \
  ansible --version; \
  aws --version; \
  aws-adfs --version; \
  git --version; \
  htop --version; \
  jq --version; \
  tmux -V; \
  tree --version; \
  wget --version
