
## Workspace Linux configuration.
## 
## Ubuntu
##
FROM ubuntu:18.04

WORKDIR /root

RUN apt-get update -y && apt-get install -y \
  build-essential \
  git \
  htop \
  jq \
  dnsutils \
  libffi-dev \
  libssl-dev \
  libxslt-dev \
  libxml2 \
  libxml2-dev \
  python \
  python-openssl \
  python-cffi \
  python-dev \
  python-pip \
  openssl \
  tmux \
  tree \
  vim \
  wget \
  curl \
  zip

RUN pip install \
  ansible \
  aws-adfs \
  awscli \
  boto3 \
  aws-shell

## Install CloudFoundry Tools

# Install cf-cli
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN apt-get update -y && apt-get install -y cf-cli && cf install-plugin -f cflocal

# Install usage-report plugin
# USAGE: cf usage-report -o <space>
RUN cf install-plugin -f 'Usage Report' -r CF-Community

RUN \
  ansible --version; \
  aws --version; \
  aws-adfs --version; \
  git --version; \
  htop --version; \
  jq --version; \
  tmux -V; \
  tree --version; \
  wget --version; \
  cf local version;
