
## Workspace Linux configuration.
## 
## Ubuntu
##
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y \
  build-essential \
  git \
  htop \
  jq \
  libffi-dev \
  libssl-dev \
  libxslt-dev \
  libxml2 \
  libxml2-dev \
  python \
  python-openssl \
  python-cffi \
  python-dev \
  python-pip \
  openssl \
  tmux \
  tree \
  vim \
  wget \
  curl \
  zip





# RUN yum -y update && yum -y install \
#   epel-release \
#   gcc \
#   git \
#   htop \
#   jq \
#   libffi-dev \
#   libffi-devel \
#   libssl-dev \
#   libxslt-devel \
#   libxml2-devel \
#   pyOpenSSL \
#   python27 \
#   python27-cffi \
#   python27-dev \
#   python27-devel \
#   python2-pip \
#   openssl-dev \
#   openssl-devel \
#   tmux \
#   tree \
#   vim \
#   wget \
#   zip


RUN pip install \
  ansible \
  aws-adfs \
  awscli \
  boto3

## Install CloudFoundry Tools

# Install cf-cli
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN apt-get update -y && apt-get install -y cf-cli && cf install-plugin -f cflocal

RUN \
  ansible --version; \
  aws --version; \
  aws-adfs --version; \
  git --version; \
  htop --version; \
  jq --version; \
  tmux -V; \
  tree --version; \
  wget --version; \
  cf local version;




