
## Workspace Linux configuration.
## 
## Ubuntu
##
FROM ubuntu:bionic

WORKDIR /root

RUN apt-get update -y && apt-get install -y \
  build-essential \
  apt-transport-https \
  software-properties-common \
  ca-certificates \
  apt-utils \
  git \
  htop \
  jq \
  dnsutils \
  libffi-dev \
  libssl-dev \
  libxslt-dev \
  libxml2 \
  libxml2-dev \
  python \
  python-openssl \
  python-cffi \
  python-dev \
  python-pip \
  openssl \
  tmux \
  tree \
  vim \
  wget \
  curl \
  groff-base \
  zip \
  nodejs \
  ruby-full \
  openjdk-8-jdk

RUN pip install \
  ansible \
  aws-adfs \
  awscli \
  boto3 \
  aws-shell

  ## Add octokit for GitHub API with Ruby
  RUN gem install octokit

## Install Docker tools, will use the host daemon via a mapped volume to the local socket /var/run/docker.sock
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    && apt-get update \
    && apt-get install -y docker-ce

## Install kubectl (k8s)
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
  echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
  apt-get update && apt-get install -y kubectl

## Install CloudFoundry Tools

# Install bosh-cli
RUN wget -q -O /usr/bin/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v5.4.0/bosh-cli-5.4.0-linux-amd64 && chmod +x /usr/bin/bosh

# Install Concourse CLI (fly)
RUN wget -q -O /usr/bin/fly https://github.com/concourse/concourse/releases/download/v4.2.3/concourse_linux_amd64 && chmod +x /usr/bin/fly

# Install cf-cli
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN apt-get update -y && apt-get install -y cf-cli && cf install-plugin -f cflocal

# Install usage-report plugin
# USAGE: cf usage-report -o <space>
RUN cf install-plugin -f 'Usage Report' -r CF-Community
RUN cf install-plugin -f 'Service Instance Logging' -r CF-Community

# Set flag to force container updates
ARG FORCE_UPGRADE=no
RUN apt-get update -y && apt-get upgrade -y

RUN \
  ansible --version; \
  aws --version; \
  aws-adfs --version; \
  git --version; \
  htop --version; \
  jq --version; \
  tmux -V; \
  tree --version; \
  wget --version; \
  ruby --version; \
  cf local version; \
  fly -v;

CMD [/bin/bash]
